# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CYFR Works Inc.

defmodule Mix.Tasks.Cyfr.Gen.ConfigurationGuide do
  @shortdoc "Render configuration-guide.md from the settings roster"

  @moduledoc """
  Renders `configuration-guide.md`, the operator's reference to every name
  the `cyfr` server reads from its environment and every platform setting,
  from `Cyfr.Platform.Settings.Roster`: the deployment variables, the
  platform settings with their key, variable, type, default, group, scope
  and stale policy, the compose-only names, the names other programs own,
  and the headless recovery procedure.

      mix cyfr.gen.configuration_guide
      mix cyfr.gen.configuration_guide --check

  `--check` fails when the file is not the render.
  """

  use Boundary, classify_to: Cyfr

  use Mix.Task

  alias Cyfr.Platform.Settings.Roster
  alias Cyfr.Platform.Settings.Roster.Entry

  @target "configuration-guide.md"

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("compile")
    path = Path.join(root(), @target)
    rendered = render()

    case args do
      ["--check"] ->
        # arca:bypass-ok=E — the render's home is a tracked file at the root.
        if File.read(path) == {:ok, rendered} do
          Mix.shell().info("#{@target} is current")
        else
          Mix.raise("#{@target} is stale — run `mix cyfr.gen.configuration_guide`")
        end

      [] ->
        # arca:bypass-ok=E
        File.write!(path, rendered)
        Mix.shell().info("wrote #{@target}")

      _other ->
        Mix.raise("usage: mix cyfr.gen.configuration_guide [--check]")
    end
  end

  @doc "The guide's path, relative to the repository root."
  @spec target() :: String.t()
  def target, do: @target

  @doc "The guide's text, from the roster."
  @spec render() :: String.t()
  def render do
    cache_s = div(Arca.PlatformSettings.ttl_ms(), 1000)

    """
    <!-- Generated by `mix cyfr.gen.configuration_guide` from Cyfr.Platform.Settings.Roster. Edit the roster and run the task; `--check` fails on a stale copy. -->

    # Configuration Guide

    The `cyfr` server has two kinds of configuration. A **deployment
    variable** is read from the environment (`.env` in the compose stack)
    before the database opens, or decides how the server is reached, or is a
    security posture a stolen operator session must not change: it changes
    with a restart. A **platform setting** is stored in the database, the
    same on every member, and a platform admin changes it on Prism's
    Settings page, with `cyfr settings`, or through the `settings` tool.

    `.env.example` is the starting `.env`: the keys and addresses `cyfr init`
    writes, and the deployment choices commented out. The execution worker's
    own settings are in `.env.opus.example` and the Locus services' in
    `.env.locus.example`. A `CYFR_*` name in the server's `.env` that no table
    below declares refuses the boot, naming it; the process environment may
    carry the names other programs own as well.

    ## Deployment variables

    | Variable | What it sets |
    |---|---|
    #{rows(Roster.deployment_docs())}

    ## Platform settings

    A setting's value is its variable's, when this member's environment sets
    it; else the stored value; else its default. A variable set in the
    environment **pins** the setting: the Settings page shows the pin and
    refuses to change it, and a member whose pin disagrees with a live
    member's refuses to boot, so a pinned value changes by stopping every
    member that holds the old pin before the first starts with the new one.

    A **live** setting's change reaches new and refreshed work on every
    member within #{cache_s} seconds, not work already in flight. A
    **restart** setting applies at each member's next start and is listed as
    pending until then.

    When the store cannot answer, the stale policy decides: **refuse**
    answers unavailable, so what the setting gates is refused rather than
    guessed; **serve** keeps the last value read, or the default.

    Every value passes the setting's validator, at boot and on every write:
    a whole number outside its range, or a value of the wrong type, is
    refused, naming the variable or key and the form it must take.

    | Variable | Key | Type | Default | Group | Scope | Stale | What it sets |
    |---|---|---|---|---|---|---|---|
    #{Enum.map_join(Roster.entries(), "\n", &setting_row/1)}

    ## Compose-only variables

    `docker-compose.yml` reads these from `.env`; no release reads them.

    | Variable | What it sets |
    |---|---|
    #{rows(Roster.compose_only_docs())}

    ## Names other programs own

    A shell may export these beside a server: the process environment
    tolerates them, and a `.env` file that assigns one refuses the boot.

    | Name | Owner |
    |---|---|
    #{Enum.map_join(Roster.foreign(), "\n", &foreign_row/1)}

    ## Headless recovery

    The settings functions are public, so an operator without the console
    reaches them through the release. `bin/cyfr rpc` changes the **running
    node**: the value is written, announced, and reaches every member as a
    change on the Settings page does.

        bin/cyfr rpc 'IO.inspect(Cyfr.Platform.Settings.list())'
        bin/cyfr rpc 'IO.inspect(Cyfr.Platform.Settings.set(Sanctum.system_context(), "log_level", "debug"))'
        bin/cyfr rpc 'IO.inspect(Cyfr.Platform.Settings.reset(Sanctum.system_context(), "log_level"))'

    `bin/cyfr eval` changes the **next boot**: with no node running, it
    starts the store's application, writes the value, and announces
    nothing; the next boot reads the store.

        bin/cyfr eval 'Application.ensure_all_started(:arca); IO.inspect(Cyfr.Platform.Settings.reset(Sanctum.system_context(), "log_level"))'

    Either way a write names the revision it was made against or reads the
    current one, and a key the environment pins is refused (`{:error,
    :pinned}`): its value is changed in the environment.
    """
  end

  defp rows(pairs), do: Enum.map_join(pairs, "\n", fn {name, doc} -> "| `#{name}` | #{doc} |" end)

  defp setting_row(%Entry{} = entry) do
    cells = [
      if(entry.variable, do: "`#{entry.variable}`", else: "—"),
      "`#{entry.key}`",
      "`#{entry.type}`",
      default(entry),
      "`#{entry.group}`",
      Atom.to_string(entry.scope),
      Atom.to_string(entry.stale),
      entry.doc || raise("#{entry.key} has no doc in the roster")
    ]

    "| " <> Enum.join(cells, " | ") <> " |"
  end

  defp default(%Entry{default: nil, inherit: true}), do: "the MCP pair's"
  defp default(%Entry{default: nil}), do: "none"
  defp default(%Entry{default: value}) when is_atom(value), do: "`#{value}`"
  defp default(%Entry{default: value}), do: "`#{inspect(value)}`"

  defp foreign_row({name, owner}) do
    case String.split_at(name, -1) do
      {prefix, "*"} -> "| `#{prefix}…` (every name it begins) | #{owner} |"
      _exact -> "| `#{name}` | #{owner} |"
    end
  end

  defp root, do: Path.expand("../../../../..", __DIR__)
end
