# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CYFR Works Inc.

defmodule Mix.Tasks.Ops.Gen.Cli do
  @shortdoc "Render the operation catalog's tool and action names for the CLI"

  @moduledoc """
  Renders every `tool.action` the operation catalog serves into
  `apps/codex/internal/ops/catalog_gen.go`: one Go constant per tool, one
  per action, and the actions per tool. The CLI's built-in commands name
  operations through these constants, so a renamed or retired action
  fails `go build`; `Cyfr.Ops.LiteralDriftTest` refuses a checked-in
  render that is stale.

      mix ops.gen.cli          # write the file
      mix ops.gen.cli --check  # exit 1 when the checked-in file is stale

  Only names are rendered: per-action argument contracts are not in the
  catalog's declarations yet.
  """

  use Mix.Task

  @target "apps/codex/internal/ops/catalog_gen.go"

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.config")
    path = Path.join(root(), @target)
    rendered = render()

    case args do
      ["--check"] ->
        # arca:bypass-ok=E — the render's home is a tracked source file.
        if current?(File.read(path), rendered) do
          Mix.shell().info("#{@target} is current")
        else
          Mix.raise("#{@target} is stale — run `mix ops.gen.cli`")
        end

      _ ->
        # arca:bypass-ok=E
        File.mkdir_p!(Path.dirname(path))
        File.write!(path, rendered)
        gofmt(path)
        Mix.shell().info("wrote #{@target}")
    end
  end

  @doc """
  Whether a checked-in file carries the render: `gofmt` aligns the
  constants, so runs of spaces are not compared.
  """
  @spec current?({:ok, String.t()} | {:error, term()}, String.t()) :: boolean()
  def current?({:ok, file}, rendered), do: squeeze(file) == squeeze(rendered)
  def current?(_missing, _rendered), do: false

  defp squeeze(text), do: Regex.replace(~r/ +/, text, " ")

  # The Go toolchain formats what it will compile; without one the file is
  # written as rendered and `gofmt` runs where the CLI is built.
  defp gofmt(path) do
    case System.find_executable("gofmt") do
      nil -> :ok
      gofmt -> {_, 0} = System.cmd(gofmt, ["-w", path])
    end
  end

  @doc "The file's text, from the loaded catalog."
  @spec render() :: String.t()
  def render do
    by_tool =
      Cyfr.Ops.Catalog.tool_actions()
      |> Enum.map(fn pair ->
        [tool, action] = String.split(pair, ".", parts: 2)
        {tool, action}
      end)
      |> Enum.group_by(&elem(&1, 0), &elem(&1, 1))
      |> Enum.map(fn {tool, actions} -> {tool, Enum.sort(actions)} end)
      |> Enum.sort()

    tools =
      Enum.map_join(by_tool, "\n", fn {tool, _} ->
        ~s(\t#{ident(tool)} = "#{tool}")
      end)

    actions =
      Enum.map_join(by_tool, "\n", fn {tool, actions} ->
        Enum.map_join(actions, "\n", fn action ->
          ~s(\t#{ident(tool)}#{ident(action)} = "#{action}")
        end)
      end)

    table =
      Enum.map_join(by_tool, "\n", fn {tool, actions} ->
        list = Enum.map_join(actions, ", ", &~s("#{&1}"))
        ~s(\t"#{tool}": {#{list}},)
      end)

    """
    // SPDX-License-Identifier: Apache-2.0
    // Copyright 2026 CYFR Works Inc.

    // Code generated by `mix ops.gen.cli`. DO NOT EDIT.

    // Package ops names the operations the server's catalog serves. A
    // built-in command names its operation through these constants; an
    // operation the catalog no longer serves fails the build here.
    package ops

    // Tools.
    const (
    #{tools}
    )

    // Actions, as tool then action.
    const (
    #{actions}
    )

    // Actions lists every action the catalog serves, per tool.
    var Actions = map[string][]string{
    #{table}
    }
    """
  end

  # `mcp_log` → `McpLog`, `skill_create` → `SkillCreate`.
  defp ident(name) do
    name
    |> String.split(~r/[^A-Za-z0-9]+/)
    |> Enum.reject(&(&1 == ""))
    |> Enum.map_join(&String.capitalize/1)
  end

  defp root do
    Path.expand("../../../../..", __DIR__)
  end
end
