# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CYFR Works Inc.

defmodule Mix.Tasks.Ops.Gen.Cli do
  @shortdoc "Render typed operation arguments for the CLI"

  @moduledoc """
  Renders external operation names and typed arguments from the catalog's
  declarations into `apps/codex/internal/ops/catalog_gen.go`. Optional fields
  preserve omission separately from an explicit zero, false, empty or null.
  Each argument struct serializes its declared action discriminator.

      mix ops.gen.cli
      mix ops.gen.cli --check
  """

  use Mix.Task

  @target "apps/codex/internal/ops/catalog_gen.go"

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.config")
    path = Path.join(root(), @target)
    rendered = render()

    case args do
      ["--check"] ->
        # arca:bypass-ok=E — the render's home is a tracked source file.
        if current?(File.read(path), rendered) do
          Mix.shell().info("#{@target} is current")
        else
          Mix.raise("#{@target} is stale — run `mix ops.gen.cli`")
        end

      _ ->
        # arca:bypass-ok=E
        File.mkdir_p!(Path.dirname(path))
        File.write!(path, rendered)
        gofmt(path)
        Mix.shell().info("wrote #{@target}")
    end
  end

  @doc """
  Whether a checked-in file carries the render, ignoring whitespace
  that `gofmt` changes around declarations and fields.
  """
  @spec current?({:ok, String.t()} | {:error, term()}, String.t()) :: boolean()
  def current?({:ok, file}, rendered), do: tokens(file) == tokens(rendered)
  def current?(_missing, _rendered), do: false

  defp tokens(text) do
    Regex.scan(
      ~r/`[^`]*`|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\/\/[^\r\n]*|\/\*[\s\S]*?\*\/|[\p{L}\p{N}_]+|<<=|>>=|&\^=|:=|==|!=|<=|>=|&&|\|\||<<|>>|&\^|\+\+|--|\.\.\.|<-|[+*\/=%&|^!-]=|\S/u,
      text
    )
  end

  # The Go toolchain formats what it will compile; without one the file is
  # written as rendered and `gofmt` runs where the CLI is built.
  defp gofmt(path) do
    case System.find_executable("gofmt") do
      nil -> :ok
      gofmt -> {_, 0} = System.cmd(gofmt, ["-w", path])
    end
  end

  @doc "The file's text, from the loaded catalog."
  @spec render() :: String.t()
  def render do
    operations =
      for provider <- Grimoire.Catalog.configured_providers(),
          tool <- provider.tools(),
          operation <- tool.operations,
          :external in operation.planes,
          do: operation

    render(operations)
  end

  @doc "Render explicit declarations, without starting the catalog."
  @spec render([Prima.Operation.t()]) :: String.t()
  def render(operations) do
    operations = Enum.sort_by(operations, &{&1.tool, &1.action})

    by_tool =
      operations
      |> Enum.group_by(& &1.tool, & &1.action)
      |> Enum.sort()

    tools =
      Enum.map_join(by_tool, "\n", fn {tool, _} ->
        ~s(\t#{ident(tool)} = "#{tool}")
      end)

    actions =
      Enum.map_join(by_tool, "\n", fn {tool, actions} ->
        Enum.map_join(actions, "\n", fn action ->
          ~s(\t#{ident(tool)}#{ident(action)} = "#{action}")
        end)
      end)

    table =
      Enum.map_join(by_tool, "\n", fn {tool, actions} ->
        list = Enum.map_join(actions, ", ", &~s("#{&1}"))
        ~s(\t"#{tool}": {#{list}},)
      end)

    """
    // SPDX-License-Identifier: Apache-2.0
    // Copyright 2026 CYFR Works Inc.

    // Code generated by `mix ops.gen.cli`. DO NOT EDIT.

    // Package ops names the operations the server's catalog serves. A
    // built-in command names its operation through these constants; an
    // operation the catalog no longer serves fails the build here.
    package ops

    import "encoding/json"

    // Tools.
    const (
    #{tools}
    )

    // Actions, as tool then action.
    const (
    #{actions}
    )

    // Actions lists every action the catalog serves, per tool.
    var Actions = map[string][]string{
    #{table}
    }

    #{Enum.map_join(operations, "\n", &operation_struct/1)}
    """
  end

  defp operation_struct(operation) do
    name = ident(operation.tool) <> ident(operation.action) <> "Args"
    {definition, nested} = record_struct(name, operation.args)

    """
    // #{name} carries arguments for #{operation.tool}.#{operation.action}.
    #{definition}
    // MarshalJSON supplies the operation's fixed action discriminator.
    func (args #{name}) MarshalJSON() ([]byte, error) {
      type fields #{name}
      return json.Marshal(struct {
        Action string `json:"action"`
        fields
      }{Action: #{ident(operation.tool)}#{ident(operation.action)}, fields: fields(args)})
    }
    #{nested}
    """
  end

  defp record_struct(name, args) do
    fields =
      Enum.map(args, fn arg ->
        {type, nested} = go_type(arg.type, name <> ident(arg.name))
        type = if arg.nullable, do: "*" <> type, else: type
        type = if arg.required, do: type, else: "Field[#{type}]"
        tag = arg.name <> if(arg.required, do: "", else: ",omitzero")
        comment = comment(arg.description)
        {"#{comment}  #{ident(arg.name)} #{type} `json:#{Jason.encode!(tag)}`", nested}
      end)

    definition = "type #{name} struct {\n#{Enum.map_join(fields, "\n", &elem(&1, 0))}\n}\n"
    {definition, Enum.map_join(fields, "\n", &elem(&1, 1))}
  end

  defp comment(nil), do: ""

  defp comment(text) do
    text
    |> String.split(~r/\R/)
    |> Enum.map_join("", &("  // " <> &1 <> "\n"))
  end

  defp go_type(:string, _name), do: {"string", ""}
  defp go_type(:integer, _name), do: {"int", ""}
  defp go_type(:number, _name), do: {"float64", ""}
  defp go_type(:boolean, _name), do: {"bool", ""}
  defp go_type(:json, _name), do: {"any", ""}

  defp go_type({:record, args}, name) do
    {definition, nested} = record_struct(name, args)

    decoder = """
    // UnmarshalJSON refuses unknown fields and preserves required presence.
    func (args *#{name}) UnmarshalJSON(data []byte) error {
      type fields #{name}
      var value fields
      if err := decodeRecord(data, &value); err != nil { return err }
      *args = #{name}(value)
      return nil
    }
    """

    {name, definition <> decoder <> nested}
  end

  defp go_type({kind, item}, name) when kind in [:array, :map] do
    {type, nested} = go_type(item.type, name <> "Item")
    type = if item.nullable, do: "*" <> type, else: type
    prefix = if kind == :array, do: "[]", else: "map[string]"
    {prefix <> type, nested}
  end

  # `mcp_log` → `McpLog`, `skill_create` → `SkillCreate`.
  defp ident(name) do
    name
    |> String.split(~r/[^A-Za-z0-9]+/)
    |> Enum.reject(&(&1 == ""))
    |> Enum.map_join(&String.capitalize/1)
  end

  defp root do
    Path.expand("../../../../..", __DIR__)
  end
end
