# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CYFR Works Inc.

defmodule EmissaryWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :cyfr

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @default_session_salt "CZdqUO1/"

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  @doc """
  Session cookie options. Public so tests can assert the security flags.
  Must emit `http_only: true`, `same_site: "Lax"`, and `secure:` tied to
  `:cookie_secure` (true in prod, false in dev/test).
  """
  def session_options do
    salt = Application.get_env(:cyfr, :emissary_session_salt, @default_session_salt)

    [
      store: :cookie,
      key: "_emissary_key",
      signing_salt: salt,
      same_site: "Lax",
      http_only: true,
      secure: Cyfr.RuntimeConfig.cookie_secure?()
    ]
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :cyfr,
    gzip: not code_reloading?,
    only: EmissaryWeb.static_paths()
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug(Phoenix.CodeReloader)
  end

  plug(EmissaryWeb.MetricsPlug)
  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Sized for the 20 MB attachment cap both chat UIs enforce (Porta's
    # agent-store MAX_ATTACHMENT_SIZE and aqua_live's max_file_size):
    # attachments arrive base64-encoded through POST /mcp, so 20 MB × 4/3
    # plus JSON envelope headroom. Webhooks keep their own smaller cap in
    # RawBodyReader.
    length: 28_000_000,
    body_reader: {EmissaryWeb.Plugs.RawBodyReader, :read_body, []}
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(:dynamic_session)
  plug(:security_headers)
  plug(EmissaryWeb.Router)

  defp dynamic_session(conn, _opts) do
    opts = Plug.Session.init(session_options())
    Plug.Session.call(conn, opts)
  end

  defp security_headers(conn, _opts) do
    headers = [
      {"x-content-type-options", "nosniff"},
      {"x-frame-options", "DENY"},
      {"referrer-policy", "strict-origin-when-cross-origin"},
      {"content-security-policy", "default-src 'none'; frame-ancestors 'none'"}
    ]

    # Add HSTS only when serving over TLS (production)
    headers =
      if conn.scheme == :https do
        [{"strict-transport-security", "max-age=63072000; includeSubDomains"} | headers]
      else
        headers
      end

    Enum.reduce(headers, conn, fn {key, value}, conn ->
      Plug.Conn.put_resp_header(conn, key, value)
    end)
  end
end
