# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CYFR Works Inc.

defmodule EmissaryWeb.Endpoint do
  @moduledoc """
  The one endpoint. The API, the MCP transport, tinctures and the Prism
  LiveViews all answer here — one origin, one cookie, one login, one
  `check_origin` — so a CM5 kiosk, a phone and a laptop each need exactly
  one URL. Headless is a deployment that omits the HTML routes, not a
  second endpoint.
  """

  use Phoenix.Endpoint, otp_app: :cyfr

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @default_session_salt "CZdqUO1/"

  @doc """
  Session cookie options. Public so tests can assert the security flags.
  Must emit `http_only: true`, `same_site: "Lax"`, and `secure:` tied to
  `:cookie_secure` (true in prod, false in dev/test). Thirty days: the
  browser session is the one credential a person's devices hold.
  """
  def session_options do
    salt = Application.get_env(:cyfr, :emissary_session_salt, @default_session_salt)

    [
      store: :cookie,
      key: "_cyfr_key",
      signing_salt: salt,
      same_site: "Lax",
      http_only: true,
      secure: Cyfr.RuntimeConfig.cookie_secure?(),
      max_age: 30 * 24 * 60 * 60
    ]
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {__MODULE__, :session_options, []}]],
    longpoll: [connect_info: [session: {__MODULE__, :session_options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :cyfr,
    gzip: not code_reloading?,
    only: EmissaryWeb.static_paths(),
    cache_static_manifest: "priv/static/cache_manifest.json"
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
  end

  plug(EmissaryWeb.MetricsPlug)
  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Sized for the 20 MB attachment cap both chat UIs enforce (Porta's
    # agent-store MAX_ATTACHMENT_SIZE and aqua_live's max_file_size):
    # attachments arrive base64-encoded through POST /mcp, so 20 MB × 4/3
    # plus JSON envelope headroom. Webhooks keep their own smaller cap in
    # RawBodyReader.
    length: 28_000_000,
    body_reader: {EmissaryWeb.Plugs.RawBodyReader, :read_body, []}
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(:dynamic_session)
  # Security headers are a pipeline concern now: the API/MCP/webhook
  # pipelines carry the closed set (`EmissaryWeb.Plugs.ApiSecurityHeaders`),
  # the browser pipeline the LiveView-compatible one
  # (`EmissaryWeb.Plugs.BrowserCSP`), and tinctures their own.
  plug(EmissaryWeb.Router)

  defp dynamic_session(conn, _opts) do
    opts = Plug.Session.init(session_options())
    Plug.Session.call(conn, opts)
  end
end
