# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CYFR Works Inc.

defmodule Compendium.BuildsTest.RefusingStore do
  @moduledoc false
  # A store that takes no artifact: every write of a `.wasm` fails.
  use Arca.Storage.TestDouble

  def put(actor, path, content) do
    if String.ends_with?(List.last(path), ".wasm"),
      do: {:error, :injected_outage},
      else: Arca.Adapters.Local.put(actor, path, content)
  end
end

defmodule Compendium.BuildsTest do
  @moduledoc """
  A build from the tool to the unit: the sources the builder is sent, the
  verified result published and registered, the started build's row and
  its progress, and what is left behind when a build does not end in a
  result. The builds service is `Cyfr.Test.ScriptedBuilder`.
  """
  use ExUnit.Case, async: false

  alias Arca.BuildRecords
  alias Compendium.Builds
  alias Compendium.Builds.Provider
  alias Compendium.ComponentPath
  alias Cyfr.Bus.Progress
  alias Cyfr.Test.ScriptedBuilder

  import Prima.Test.Wait

  @wasm File.read!(Path.join(__DIR__, "../../support/test_wasm/math.wasm"))
  @reference "reagent:local.adder:0.1.0"
  @unit ComponentPath.version_dir("reagent", "local", "adder", "0.1.0")
  @wasm_path ComponentPath.wasm_path("reagent", "local", "adder", "0.1.0")
  @lock "# This file is automatically @generated by Cargo.\nversion = 4\n"

  setup tags do
    Cyfr.Test.Sandbox.setup!(tags)

    dir = Path.join(System.tmp_dir!(), "builds_#{System.unique_integer([:positive])}")
    prev = Application.get_env(:arca, :base_path)
    Application.put_env(:arca, :base_path, dir)

    on_exit(fn ->
      if prev, do: Application.put_env(:arca, :base_path, prev)
      File.rm_rf!(dir)
    end)

    # Registered after the restore, so it runs before it: a build's tasks
    # stop while the tree they write is still theirs.
    Cyfr.Test.Sandbox.stop_work_on_exit()
    ScriptedBuilder.start!()

    ctx = Sanctum.TestContext.local()
    :ok = Arca.ensure_roots(Sanctum.Context.actor(ctx))
    {:ok, _} = Compendium.Scaffold.create(ctx, "adder", "reagent", "0.1.0")

    {:ok, ctx: ctx}
  end

  defp component(outputs \\ %{}) do
    %{
      language: :rust,
      target_type: :reagent,
      outputs: Map.merge(%{"component.wasm" => @wasm}, outputs),
      diagnostics: []
    }
  end

  defp compile(ctx, extra \\ %{}) do
    Provider.handle(
      "build",
      ctx,
      Map.merge(%{"action" => "compile", "reference" => @reference}, extra)
    )
  end

  defp status(ctx, build_id),
    do: Provider.handle("build", ctx, %{"action" => "status", "build_id" => build_id})

  defp registered?(ctx) do
    match?({:ok, _}, Compendium.Registry.get(ctx, "adder", "0.1.0", "local", "reagent"))
  end

  describe "a component build" do
    test "sends the unit's sources, publishes the verified bytes and the lock, and registers", %{
      ctx: ctx
    } do
      {:ok, real} = Prima.Wasm.validate(@wasm)

      ScriptedBuilder.script([
        {:stream,
         [
           {:progress, :compiling, "Compiling reagent (rust)..."},
           {:result, component(%{"Cargo.lock" => @lock})}
         ]}
      ])

      refute registered?(ctx)
      assert {:ok, result} = compile(ctx)

      assert result == %{
               status: "compiled",
               reference: @reference,
               digest: real.digest,
               size: real.size,
               files: [],
               exports: real.exports,
               language: "rust",
               target_type: "reagent",
               registration: "pending"
             }

      # The builder was sent the unit's build input and nothing else of it.
      assert [request] = ScriptedBuilder.requests()
      assert request.athanor_id == ctx.athanor_id
      assert request.language == :rust and request.target_type == :reagent
      refute request.resolve

      assert {:ok, lib_rs} =
               Arca.get(Sanctum.Context.actor(ctx), @unit ++ ["src", "src", "lib.rs"])

      assert request.sources["src/lib.rs"] == lib_rs
      assert Map.has_key?(request.sources, "Cargo.toml")
      assert Enum.all?(Map.keys(request.sources), &(&1 =~ ~r/(\.rs|\.wit|Cargo\.toml)$/))

      # Published into the unit, and registered from there.
      assert {:ok, @wasm} = Arca.get(Sanctum.Context.actor(ctx), @wasm_path)
      assert {:ok, @lock} = Arca.get(Sanctum.Context.actor(ctx), @unit ++ ["src", "Cargo.lock"])
      wait_until(fn -> registered?(ctx) end, 10_000, "the built component to be registered")

      assert {:ok, component} = Compendium.Registry.get(ctx, "adder", "0.1.0", "local", "reagent")
      assert component.digest == real.digest
      ScriptedBuilder.await_builds()
    end

    test "is locked to the unit's Cargo.lock, which resolve asks the builder to resolve afresh",
         %{ctx: ctx} do
      :ok = Arca.put(Sanctum.Context.actor(ctx), @unit ++ ["src", "Cargo.lock"], @lock)
      relocked = @lock <> "# resolved afresh\n"

      ScriptedBuilder.script([
        {:stream, [{:result, component(%{"Cargo.lock" => @lock})}]},
        {:stream, [{:result, component(%{"Cargo.lock" => relocked})}]}
      ])

      assert {:ok, _} = compile(ctx)
      assert {:ok, _} = compile(ctx, %{"resolve" => true})

      assert [locked, resolved] = ScriptedBuilder.requests()
      assert locked.sources["Cargo.lock"] == @lock
      refute locked.resolve
      assert resolved.resolve

      assert {:ok, ^relocked} =
               Arca.get(Sanctum.Context.actor(ctx), @unit ++ ["src", "Cargo.lock"])

      ScriptedBuilder.await_builds()
    end
  end

  describe "a started build" do
    test "answers its id at once; its row reads started, then carries the result and the registration",
         %{ctx: ctx} do
      test = self()
      ScriptedBuilder.script([{:stream, [{:hold, test}, {:result, component()}]}])

      assert {:ok, %{status: "started", build_id: "build_row", reference: @reference}} =
               compile(ctx, %{"async" => true, "build_id" => "build_row"})

      assert_receive {:scripted_builder, :holding, handler}, 5_000
      assert {:ok, %{"status" => "started", "reference" => @reference}} = status(ctx, "build_row")

      # An id naming a build still in flight is not taken by another.
      assert {:error, {:invalid_argument, in_flight}} =
               compile(ctx, %{"async" => true, "build_id" => "build_row"})

      assert in_flight =~ "still in flight"

      send(handler, :continue)

      wait_until(
        fn -> match?({:ok, %{"status" => "compiled"}}, status(ctx, "build_row")) end,
        10_000,
        "the build's row to carry its result"
      )

      assert {:ok, @wasm} = Arca.get(Sanctum.Context.actor(ctx), @wasm_path)

      wait_until(
        fn ->
          match?(
            {:ok, %{"result" => %{"registration" => "done"}}},
            status(ctx, "build_row")
          )
        end,
        10_000,
        "the build's row to carry its registration"
      )

      assert registered?(ctx)
      ScriptedBuilder.await_builds()
    end

    test "that the builder refuses carries the refusal on its row", %{ctx: ctx} do
      ScriptedBuilder.script([{:refuse, {:failed, {:status, 101}}, ["output: error[E0425]"]}])

      assert {:ok, %{status: "started", build_id: build_id}} = compile(ctx, %{"async" => true})

      wait_until(
        fn -> match?({:ok, %{"status" => "failed"}}, status(ctx, build_id)) end,
        10_000,
        "the build's row to carry its failure"
      )

      assert {:ok, %{"error" => error}} = status(ctx, build_id)
      assert error == "Compilation failed (exit 101): output: error[E0425]"
      refute Arca.exists?(Sanctum.Context.actor(ctx), @wasm_path)
      ScriptedBuilder.await_builds()
    end

    test "whose process is killed while the builder works: the request ends, nothing is published, its row says failed",
         %{ctx: ctx} do
      ScriptedBuilder.script([{:stream, [{:progress, :compiling, "…"}, {:hold, self()}]}])

      assert {:ok, %{status: "started"}} =
               compile(ctx, %{"async" => true, "build_id" => "build_killed"})

      assert_receive {:scripted_builder, :holding, _handler}, 5_000

      # The runner is the process the request is linked to.
      runner = runner!()
      Process.exit(runner, :kill)

      assert_receive {:scripted_builder, :disconnected}, 5_000

      wait_until(
        fn -> match?({:ok, %{"status" => "failed"}}, status(ctx, "build_killed")) end,
        10_000,
        "the killed build's row to be closed"
      )

      assert {:ok, %{"error" => error}} = status(ctx, "build_killed")
      assert error =~ "ended before its outcome was recorded"
      refute Arca.exists?(Sanctum.Context.actor(ctx), @wasm_path)
      refute registered?(ctx)
      ScriptedBuilder.await_builds()
    end
  end

  # The started build's process: the one the request's process names as its
  # caller.
  defp runner! do
    children = Task.Supervisor.children(Compendium.Builds.TaskSupervisor)

    Enum.find_value(children, fn pid ->
      with {:dictionary, dictionary} <- Process.info(pid, :dictionary),
           [caller | _] <- dictionary[:"$callers"],
           true <- caller in children do
        caller
      else
        _ -> nil
      end
    end) || flunk("no started build is running")
  end

  describe "a build whose caller goes away" do
    test "killed while the builder works: the request ends and nothing is published", %{ctx: ctx} do
      test = self()
      ScriptedBuilder.script([{:stream, [{:progress, :compiling, "…"}, {:hold, test}]}])

      # What a cancelled or timed-out tool call does to the process its
      # handler runs on.
      caller =
        spawn(fn -> send(test, {:answered, compile(ctx, %{"build_id" => "build_sync"})}) end)

      assert_receive {:scripted_builder, :holding, _handler}, 5_000
      Process.exit(caller, :kill)

      assert_receive {:scripted_builder, :disconnected}, 5_000
      refute_received {:answered, _}
      refute Arca.exists?(Sanctum.Context.actor(ctx), @wasm_path)
      refute registered?(ctx)
      # A build on its caller's process has no row: its caller was its record.
      assert {:error, :not_found} = BuildRecords.get(Sanctum.Context.actor(ctx), "build_sync")
    end
  end

  describe "progress" do
    test "reaches the build's topic and the request's MCP stream in the builder's order, then completion",
         %{ctx: ctx} do
      test = self()
      ctx = %{ctx | request_id: "req_build_progress"}
      actor = Sanctum.Context.actor(ctx)
      :ok = Cyfr.Bus.subscribe(actor, Cyfr.Bus.progress(actor, {:build, "build_watched"}))
      _listener = request_listener(actor, "req_build_progress", "tok-build")

      ScriptedBuilder.script([
        {:stream,
         [
           {:progress, :preparing, "Preparing source files..."},
           {:hold, test},
           {:progress, :compiling, "Compiling reagent (rust)..."},
           {:progress, :output, "   Compiling adder v0.1.0"},
           {:progress, :validating, "Validating WASM binary..."},
           {:result, component()}
         ]}
      ])

      task = Task.async(fn -> compile(ctx, %{"build_id" => "build_watched"}) end)

      # The first line is on the topic while the builder still works.
      assert_receive {:scripted_builder, :holding, handler}, 5_000

      assert_receive %Progress{
        subject: {:build, "build_watched"},
        request_id: "req_build_progress",
        phase: :preparing,
        message: "Preparing source files..."
      }

      send(handler, :continue)
      assert {:ok, %{status: "compiled"}} = Task.await(task, 10_000)

      assert [:compiling, :output, :validating, :complete] ==
               Enum.map(1..4, fn _ ->
                 assert_received %Progress{subject: {:build, _}, phase: phase, at: at}
                 assert is_binary(at)
                 phase
               end)

      refute_received %Progress{}

      notified =
        for _ <- 1..5 do
          assert_receive {:notified, %{"method" => "notifications/progress", "params" => p}},
                         5_000

          assert p["progressToken"] == "tok-build"
          assert p["build_id"] == "build_watched"
          to_string(p["phase"])
        end

      assert notified == ~w(preparing compiling output validating complete)
      ScriptedBuilder.await_builds()
    end

    test "ends in an error step when the build does not", %{ctx: ctx} do
      actor = Sanctum.Context.actor(ctx)
      :ok = Cyfr.Bus.subscribe(actor, Cyfr.Bus.progress(actor, {:build, "build_failing"}))

      ScriptedBuilder.script([
        {:stream, [{:progress, :compiling, "…"}, {:refusal, {:failed, {:signal, "KILL"}}, []}]}
      ])

      assert {:error, _} = compile(ctx, %{"build_id" => "build_failing"})
      assert_received %Progress{phase: :compiling}
      assert_received %Progress{phase: :error, message: "Build failed"}
    end
  end

  # A stand-in for the connection streaming the request's response: bound
  # to its token and subscribed to its request's progress, forwarding each
  # notification it renders.
  defp request_listener(actor, request_id, token) do
    test = self()

    pid =
      spawn_link(fn ->
        :ok = Emissary.MCP.Progress.listen(request_id, token)
        :ok = Cyfr.Bus.subscribe(actor, Cyfr.Bus.progress(actor, {:request, request_id}))
        send(test, {:listening, self()})
        relay(test)
      end)

    receive do
      {:listening, ^pid} -> pid
    after
      5_000 -> flunk("the request listener never subscribed")
    end
  end

  defp relay(test) do
    receive do
      %Progress{} = step ->
        with {:ok, notification} <- Emissary.MCP.Progress.notification(step),
             do: send(test, {:notified, notification})

        relay(test)
    end
  end

  describe "a build that does not end in a verified result" do
    test "publishes nothing and registers nothing, however it ends", %{ctx: ctx} do
      tampered =
        ScriptedBuilder.fixture()["invalid_lines"]
        |> Enum.find(&(&1["name"] == "result_tampered_bytes"))
        |> Map.fetch!("body")

      endings = [
        {:refuse, {:capacity, 2}},
        {:stream, [{:refusal, {:memory, 1_073_741_824}, []}]},
        {:stream, [{:progress, :compiling, "…"}]},
        {:stream, [{:progress, :compiling, "…"}, :drop]},
        {:stream, [{:line, "garbage"}, {:result, component()}]},
        {:stream, [{:line, tampered}]},
        {:stream, [{:result, component(%{"component.wasm" => "not wasm"})}]},
        {:stream, [{:result, %{component() | target_type: :catalyst}}]}
      ]

      ScriptedBuilder.script(endings)

      ExUnit.CaptureLog.capture_log(fn ->
        for _ending <- endings, do: assert({:error, _} = compile(ctx))
      end)

      assert length(ScriptedBuilder.requests()) == length(endings)
      refute Arca.exists?(Sanctum.Context.actor(ctx), @wasm_path)
      refute Arca.exists?(Sanctum.Context.actor(ctx), @unit ++ ["src", "Cargo.lock"])
      refute registered?(ctx)
    end

    test "a deadline passing while the builder works ends the request as a timeout", %{ctx: ctx} do
      ScriptedBuilder.script([{:stream, [{:progress, :compiling, "…"}, {:hold, self()}]}])

      assert {:error, {:timeout, message}} = Builds.compile(ctx, @reference, budget_ms: 200)
      assert message =~ "deadline"
      assert_receive {:scripted_builder, :holding, _handler}, 5_000
      assert_receive {:scripted_builder, :disconnected}, 5_000
      refute Arca.exists?(Sanctum.Context.actor(ctx), @wasm_path)
    end

    test "a store that refuses the artifact is the build store unavailable, not a build", %{
      ctx: ctx
    } do
      ScriptedBuilder.script([{:stream, [{:result, component()}]}])

      prev = Application.get_env(:arca, :storage_adapter)
      Application.put_env(:arca, :storage_adapter, Compendium.BuildsTest.RefusingStore)

      on_exit(fn ->
        if prev,
          do: Application.put_env(:arca, :storage_adapter, prev),
          else: Application.delete_env(:arca, :storage_adapter)
      end)

      log =
        ExUnit.CaptureLog.capture_log(fn ->
          assert {:error, {:unavailable, "The build store"}} = compile(ctx)
        end)

      assert log =~ "the built artifact was not saved"
      refute Arca.exists?(Sanctum.Context.actor(ctx), @wasm_path)
      refute registered?(ctx)
    end
  end

  describe "validating bytes" do
    # A refusal whose reason is a tuple carries the binary's own bytes or
    # sizes after its tag; the answer is the tag, spelled as the builder
    # names it, never as a term.
    test "a tuple refusal answers its tag", %{ctx: ctx} do
      unsupported = <<0x00, 0x61, 0x73, 0x6D, 0x02, 0x00, 0x00, 0x00>>

      assert {:ok, %{valid: false, reason: "unsupported_version"}} =
               Provider.handle("build", ctx, %{
                 "action" => "validate",
                 "wasm_base64" => Base.encode64(unsupported)
               })

      assert {:ok, %{valid: false, reason: "invalid_magic_bytes"}} =
               Provider.handle("build", ctx, %{
                 "action" => "validate",
                 "wasm_base64" => Base.encode64("not a wasm binary")
               })
    end
  end
end
