# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CYFR Works Inc.

defmodule Opus.ExecutionEventBuffer do
  @moduledoc """
  Thin event buffer for formula execution streaming.

  Broadcasts events via PubSub and maintains a short-lived replay buffer
  in Arca.Cache so that late-joining SSE clients can catch up.

  Uses a per-execution GenServer to serialize buffer writes, preventing the
  race condition where concurrent events could be lost in a non-atomic
  read-modify-write cycle.

  Cache keys and topics are scoped by the owning athanor; a producer without
  a resolved athanor has nowhere to route to and its event is dropped, loudly.

  ## Usage

      # Formula host function pushes events:
      Opus.ExecutionEventBuffer.push(execution_id, data, sequence)

      # Executor pushes terminal events:
      Opus.ExecutionEventBuffer.push_terminal(execution_id, "complete", data, seq)

      # SSE controller replays on connect:
      events = Opus.ExecutionEventBuffer.since(execution_id, last_sequence, athanor_id)

      # Subscribe/unsubscribe to live events:
      Opus.ExecutionEventBuffer.subscribe(execution_id, ctx)
      Opus.ExecutionEventBuffer.unsubscribe(execution_id, ctx)
  """

  # Restart on crashes, but allow normal idle-timeout exits to reap the buffer.
  use GenServer, restart: :transient

  require Logger

  @max_events 50
  @buffer_ttl_ms :timer.minutes(10)
  @idle_timeout :timer.minutes(2)

  # Use the application's supervised PubSub instance.
  defp pubsub, do: Emissary.PubSub

  defp put_provenance(event, opts) do
    case Keyword.get(opts, :origin) do
      nil -> event
      origin -> event |> Map.put(:origin, origin) |> maybe_put_node(opts)
    end
  end

  defp maybe_put_node(event, opts) do
    case Keyword.get(opts, :node) do
      nil -> event
      node -> Map.put(event, :node, node)
    end
  end

  # ============================================================================
  # Public API
  # ============================================================================

  @doc """
  Push an intermediate event from a formula's `emit` host function.

  ## Options

  - `:origin` - `"guest"` (with `:node`, the emitting component) for
    guest-authored events on the authority path, `"host"` for events the
    host itself emits (setup_required). Every producer stamps one; a
    consumer must still treat an origin-less event as untrusted.
  """
  def push(execution_id, data, sequence, ctx \\ nil, opts \\ []) do
    event =
      %{
        type: "emit",
        execution_id: execution_id,
        sequence: sequence,
        timestamp: DateTime.utc_now() |> DateTime.to_iso8601(),
        data: data
      }
      |> put_provenance(opts)

    deliver(execution_id, ctx, event)
  end

  @doc """
  Push a terminal event (complete/error) from the Executor. Terminal
  events are host-generated by construction and say so.
  """
  def push_terminal(execution_id, type, data, sequence, ctx \\ nil) do
    event = %{
      type: type,
      execution_id: execution_id,
      sequence: sequence,
      timestamp: DateTime.utc_now() |> DateTime.to_iso8601(),
      data: data,
      origin: "host"
    }

    result = deliver(execution_id, ctx, event)

    # Retire the sequence counter only after the terminal event; idle buffer restarts must preserve it.
    Opus.ExecutionEventBuffer.Sequence.forget(execution_id)

    result
  end

  # Write to the athanor’s buffer synchronously before broadcasting.
  # Drop and log events without an athanor; never use a default tenant.
  defp deliver(execution_id, ctx, event) do
    case extract_athanor_id(ctx) do
      {:ok, athanor_id} ->
        buffer_event(execution_id, athanor_id, event)
        broadcast(execution_id, athanor_id, event)
        :ok

      :error ->
        Logger.error(
          "[ExecutionEventBuffer] dropping #{event.type} event for #{execution_id}: " <>
            "producer carries no athanor_id"
        )

        :telemetry.execute([:cyfr, :opus, :execution_events, :broadcast_failure], %{count: 1}, %{
          execution_id: execution_id,
          type: event.type,
          reason: :missing_athanor
        })

        :ok
    end
  end

  defp broadcast(execution_id, athanor_id, event) do
    topic = Cyfr.Topics.execution_events(execution_id, athanor_id)

    case Phoenix.PubSub.broadcast(pubsub(), topic, {:execution_event, event}) do
      :ok ->
        :ok

      {:error, reason} ->
        Logger.error(
          "[ExecutionEventBuffer] PubSub broadcast failed for #{execution_id}: #{inspect(reason)}"
        )

        :telemetry.execute([:cyfr, :opus, :execution_events, :broadcast_failure], %{count: 1}, %{
          execution_id: execution_id,
          type: event.type
        })
    end
  end

  @doc """
  Flush pending buffer writes for a given execution. Buffer writes are
  synchronous calls now, so this is a round-trip that proves the queue is
  drained; kept for test use.
  """
  def flush(execution_id) do
    case Registry.lookup(Opus.ExecutionEventBuffer.Registry, execution_id) do
      [{pid, _}] -> GenServer.call(pid, :flush)
      [] -> :ok
    end
  rescue
    _e in [ArgumentError, RuntimeError] -> :ok
  end

  @doc """
  Retrieve buffered events with sequence > `last_sequence` for an execution
  of `athanor_id`. Used for SSE reconnection replay. The athanor is required:
  the buffer is keyed by it and there is no default to read from.
  """
  def since(execution_id, last_sequence, athanor_id)
      when is_binary(athanor_id) and athanor_id != "" do
    case Arca.Cache.get(Arca.Cache.Keys.exec_events(execution_id, athanor_id)) do
      {:ok, events} -> Enum.filter(events, fn e -> e.sequence > last_sequence end)
      :miss -> []
    end
  end

  def since(execution_id, _last_sequence, athanor_id) do
    raise ArgumentError,
          "Opus.ExecutionEventBuffer.since/3: a resolved athanor_id is required " <>
            "for #{execution_id}, got #{inspect(athanor_id)}"
  end

  @doc """
  Subscribe the calling process to live events for an execution of the
  context's athanor.
  """
  def subscribe(execution_id, ctx) do
    Phoenix.PubSub.subscribe(pubsub(), topic(execution_id, ctx))
  end

  @doc """
  Unsubscribe the calling process from execution events.
  """
  def unsubscribe(execution_id, ctx) do
    Phoenix.PubSub.unsubscribe(pubsub(), topic(execution_id, ctx))
  end

  @doc """
  PubSub topic for a given execution, scoped by the owning athanor.

  `ctx` may be a full `Sanctum.Context` or anything carrying `:athanor_id`
  (an `Arca.Execution` record — the natural source at terminal-event sites).
  A caller without a resolved athanor raises: there is no default tenant to
  route to.
  """
  def topic(execution_id, ctx) do
    case extract_athanor_id(ctx) do
      {:ok, athanor_id} ->
        Cyfr.Topics.execution_events(execution_id, athanor_id)

      :error ->
        raise ArgumentError,
              "Opus.ExecutionEventBuffer.topic/2: a resolved athanor_id is required " <>
                "for #{execution_id}, got #{inspect(ctx)}"
    end
  end

  # ============================================================================
  # GenServer - Per-execution buffer serialization
  # ============================================================================

  def start_link({execution_id, athanor_id}) do
    GenServer.start_link(__MODULE__, {execution_id, athanor_id}, name: via(execution_id))
  end

  defp via(execution_id) do
    {:via, Registry, {Opus.ExecutionEventBuffer.Registry, execution_id}}
  end

  @impl true
  def init({execution_id, athanor_id}) do
    Process.flag(:trap_exit, true)

    # Restore cached events after an idle restart so reconnecting clients retain their replay window.
    events =
      case Arca.Cache.get(Arca.Cache.Keys.exec_events(execution_id, athanor_id)) do
        {:ok, cached} when is_list(cached) -> cached
        _ -> []
      end

    # If the counter table restarted while the cache survived (the
    # ExecutionTree came back mid-run), a fresh counter would re-number
    # from 1 under sequences already in the replay window. Floor it to the
    # highest cached sequence so the next emit continues the stream.
    max_seq =
      events
      |> Enum.map(&Map.get(&1, :sequence, 0))
      |> Enum.max(fn -> 0 end)

    if max_seq > 0 do
      Opus.ExecutionEventBuffer.Sequence.reseed(execution_id, max_seq)
    end

    {:ok, %{execution_id: execution_id, athanor_id: athanor_id, events: events}, @idle_timeout}
  end

  @impl true
  def handle_call(:flush, _from, state) do
    {:reply, :ok, state, @idle_timeout}
  end

  # A call, not a cast: `deliver/3` broadcasts only after this returns, so
  # the replay buffer can never lag the live stream. The emit path is
  # rate-limited; the round-trip is fine.
  def handle_call({:buffer, event}, _from, state) do
    events = (state.events ++ [event]) |> Enum.take(-@max_events)

    Arca.Cache.put(
      Arca.Cache.Keys.exec_events(state.execution_id, state.athanor_id),
      events,
      @buffer_ttl_ms
    )

    {:reply, :ok, %{state | events: events}, @idle_timeout}
  end

  @impl true
  def handle_info(:timeout, state) do
    {:stop, :normal, state}
  end

  @impl true
  def handle_info(msg, state) do
    Cyfr.UnexpectedMessage.log(__MODULE__, msg)
    {:noreply, state, @idle_timeout}
  end

  @impl true
  def terminate(_reason, state) do
    # Preserve the counter across idle buffer shutdown: replay entries and
    # executions may outlive this process. Terminal pushes retire it.
    if state.events != [] do
      key = Arca.Cache.Keys.exec_events(state.execution_id, state.athanor_id)

      # Merge with (never clobber) anything the direct-write fallback put in
      # the cache while this process existed — a wholesale put would erase
      # those events. Order can interleave; losing events cannot.
      cached =
        case Arca.Cache.get(key) do
          {:ok, existing} when is_list(existing) -> existing
          _ -> []
        end

      merged = Enum.uniq(cached ++ state.events) |> Enum.take(-@max_events)
      Arca.Cache.put(key, merged, @buffer_ttl_ms)
    end

    :ok
  end

  # ============================================================================
  # Private
  # ============================================================================

  # Route buffer writes through a per-execution GenServer to serialize them.
  # Synchronous: the caller broadcasts only after the write landed. Falls
  # back to direct cache write if the GenServer can't be started (e.g.,
  # Registry not available in tests) or dies between lookup and call —
  # non-atomic, but the event is never lost.
  defp buffer_event(execution_id, athanor_id, event) do
    case ensure_buffer(execution_id, athanor_id) do
      {:ok, pid} ->
        try do
          GenServer.call(pid, {:buffer, event})
        catch
          :exit, _reason -> buffer_event_direct(execution_id, athanor_id, event)
        end

      :error ->
        buffer_event_direct(execution_id, athanor_id, event)
    end
  end

  defp ensure_buffer(execution_id, athanor_id) do
    case Registry.lookup(Opus.ExecutionEventBuffer.Registry, execution_id) do
      [{pid, _}] ->
        {:ok, pid}

      [] ->
        case DynamicSupervisor.start_child(
               Opus.ExecutionEventBuffer.Supervisor,
               {__MODULE__, {execution_id, athanor_id}}
             ) do
          {:ok, pid} ->
            {:ok, pid}

          {:error, {:already_started, pid}} ->
            {:ok, pid}

          {:error, reason} ->
            # Not the "infrastructure absent" case — the supervisor is up
            # and refused. Log it: the direct-write fallback masks the
            # failure otherwise.
            Logger.warning(
              "#{__MODULE__}: start_child failed for #{execution_id}: #{inspect(reason)}"
            )

            :error
        end
    end
  rescue
    # Registry/Supervisor not started (e.g., in tests)
    _e in [ArgumentError, RuntimeError] -> :error
  end

  # Direct fallback for when GenServer infrastructure isn't available
  defp buffer_event_direct(execution_id, athanor_id, event) do
    key = Arca.Cache.Keys.exec_events(execution_id, athanor_id)

    events =
      case Arca.Cache.get(key) do
        {:ok, existing} -> existing
        :miss -> []
      end

    Arca.Cache.put(key, (events ++ [event]) |> Enum.take(-@max_events), @buffer_ttl_ms)
  end

  # The athanor carried by a context or an execution record.
  defp extract_athanor_id(%{athanor_id: athanor_id})
       when is_binary(athanor_id) and athanor_id != "",
       do: {:ok, athanor_id}

  defp extract_athanor_id(_), do: :error
end
