# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CYFR Works Inc.

defmodule Opus.ExecutionEventBuffer do
  @moduledoc """
  Thin event buffer for formula execution streaming.

  Broadcasts events via PubSub and maintains a short-lived replay buffer
  in Arca.Cache so that late-joining SSE clients can catch up.

  Uses a per-execution GenServer to serialize buffer writes, preventing the
  race condition where concurrent events could be lost in a non-atomic
  read-modify-write cycle.

  Cache keys are scoped by org_id for tenant isolation in tenant-scoped deployments.

  ## Usage

      # Formula host function pushes events:
      Opus.ExecutionEventBuffer.push(execution_id, data, sequence)

      # Executor pushes terminal events:
      Opus.ExecutionEventBuffer.push_terminal(execution_id, "complete", data, seq)

      # SSE controller replays on connect:
      events = Opus.ExecutionEventBuffer.since(execution_id, last_sequence)

      # Subscribe/unsubscribe to live events:
      Opus.ExecutionEventBuffer.subscribe(execution_id)
      Opus.ExecutionEventBuffer.unsubscribe(execution_id)
  """

  use GenServer
  require Logger

  @max_events 50
  @buffer_ttl_ms :timer.minutes(10)
  @idle_timeout :timer.minutes(2)

  # The application's single supervised PubSub. The old `:cyfr, :pubsub` knob was
  # never set anywhere; the name is a compile-time constant.
  defp pubsub, do: Emissary.PubSub

  defp put_provenance(event, opts) do
    case Keyword.get(opts, :origin) do
      nil -> event
      origin -> event |> Map.put(:origin, origin) |> maybe_put_node(opts)
    end
  end

  defp maybe_put_node(event, opts) do
    case Keyword.get(opts, :node) do
      nil -> event
      node -> Map.put(event, :node, node)
    end
  end

  # ============================================================================
  # Public API
  # ============================================================================

  @doc """
  Push an intermediate event from a formula's `emit` host function.

  ## Options

  - `:origin` - `"guest"` (with `:node`, the emitting component) for
    guest-authored events on the authority path, `"host"` for events the
    host itself emits (setup_required). Every producer stamps one; a
    consumer must still treat an origin-less event as untrusted.
  """
  def push(execution_id, data, sequence, ctx \\ nil, opts \\ []) do
    org_id = extract_org_id(ctx)

    event =
      %{
        type: "emit",
        execution_id: execution_id,
        sequence: sequence,
        timestamp: DateTime.utc_now() |> DateTime.to_iso8601(),
        data: data
      }
      |> put_provenance(opts)

    case Phoenix.PubSub.broadcast(pubsub(), topic(execution_id, ctx), {:execution_event, event}) do
      :ok ->
        :ok

      {:error, reason} ->
        Logger.error(
          "[ExecutionEventBuffer] PubSub broadcast failed for #{execution_id}: #{inspect(reason)}"
        )

        :telemetry.execute([:cyfr, :execution_events, :broadcast_failure], %{count: 1}, %{
          execution_id: execution_id
        })
    end

    buffer_event(execution_id, org_id, event)
    :ok
  end

  @doc """
  Push a terminal event (complete/error) from the Executor. Terminal
  events are host-generated by construction and say so.
  """
  def push_terminal(execution_id, type, data, sequence, ctx \\ nil) do
    org_id = extract_org_id(ctx)

    event = %{
      type: type,
      execution_id: execution_id,
      sequence: sequence,
      timestamp: DateTime.utc_now() |> DateTime.to_iso8601(),
      data: data,
      origin: "host"
    }

    case Phoenix.PubSub.broadcast(pubsub(), topic(execution_id, ctx), {:execution_event, event}) do
      :ok ->
        :ok

      {:error, reason} ->
        Logger.error(
          "[ExecutionEventBuffer] PubSub broadcast failed for terminal event #{execution_id}: #{inspect(reason)}"
        )

        :telemetry.execute([:cyfr, :execution_events, :broadcast_failure], %{count: 1}, %{
          execution_id: execution_id,
          type: type
        })
    end

    buffer_event(execution_id, org_id, event)
    :ok
  end

  @doc """
  Flush pending buffer writes for a given execution. Forces all prior casts
  to be processed before returning. For test use.
  """
  def flush(execution_id) do
    case Registry.lookup(Opus.ExecutionEventBuffer.Registry, execution_id) do
      [{pid, _}] -> GenServer.call(pid, :flush)
      [] -> :ok
    end
  rescue
    _e in [ArgumentError, RuntimeError] -> :ok
  end

  @doc """
  Retrieve buffered events with sequence > `last_sequence`.
  Used for SSE reconnection replay.
  """
  def since(execution_id, last_sequence, org_id \\ nil) do
    org_id = Arca.QueryHelpers.normalize_org_id(org_id)

    case Arca.Cache.get({:exec_events, execution_id, org_id}) do
      {:ok, events} -> Enum.filter(events, fn e -> e.sequence > last_sequence end)
      :miss -> []
    end
  end

  @doc """
  Subscribe the calling process to live events for an execution.
  """
  def subscribe(execution_id, ctx \\ nil) do
    Phoenix.PubSub.subscribe(pubsub(), topic(execution_id, ctx))
  end

  @doc """
  Unsubscribe the calling process from execution events.
  """
  def unsubscribe(execution_id, ctx \\ nil) do
    Phoenix.PubSub.unsubscribe(pubsub(), topic(execution_id, ctx))
  end

  @doc """
  PubSub topic for a given execution, scoped by tenant context.

  A call without a tenant context (or one whose `org_id` is unresolved) routes
  to the single-user sentinel `org_id: "local"` / `project_id: "default"` — the
  out-of-the-box workspace. Multi-tenant callers pass the execution's context so
  events route to the owning tenant.
  """
  def topic(execution_id, ctx \\ nil) do
    Sanctum.PubSub.topic("execution:events:#{execution_id}", resolve_topic_ctx(ctx))
  end

  # Resolve the tenant context for routing. Producers may pass a full
  # `Sanctum.Context` or anything carrying tenant coordinates (an
  # `Arca.Execution` record — the natural source at terminal-event sites).
  # Absent/unresolved org_id maps to the single-user `"local"`/`"default"`
  # sentinel so the topic is always valid.
  defp resolve_topic_ctx(%Sanctum.Context{org_id: org_id} = ctx)
       when is_binary(org_id) and org_id != "" do
    %{ctx | project_id: ctx.project_id || "default"}
  end

  defp resolve_topic_ctx(%{org_id: org_id} = coords)
       when is_binary(org_id) and org_id != "" do
    %Sanctum.Context{org_id: org_id, project_id: Map.get(coords, :project_id) || "default"}
  end

  defp resolve_topic_ctx(_) do
    %Sanctum.Context{
      org_id: Arca.Tenant.local_org(),
      project_id: Arca.Tenant.default_project()
    }
  end

  # ============================================================================
  # GenServer - Per-execution buffer serialization
  # ============================================================================

  def start_link({execution_id, org_id}) do
    GenServer.start_link(__MODULE__, {execution_id, org_id}, name: via(execution_id))
  end

  def start_link(execution_id) do
    GenServer.start_link(
      __MODULE__,
      {execution_id, Arca.QueryHelpers.normalize_org_id(nil)},
      name: via(execution_id)
    )
  end

  defp via(execution_id) do
    {:via, Registry, {Opus.ExecutionEventBuffer.Registry, execution_id}}
  end

  @impl true
  def init({execution_id, org_id}) do
    Process.flag(:trap_exit, true)
    {:ok, %{execution_id: execution_id, org_id: org_id, events: []}, @idle_timeout}
  end

  @impl true
  def handle_call(:flush, _from, state) do
    {:reply, :ok, state, @idle_timeout}
  end

  @impl true
  def handle_cast({:buffer, event}, state) do
    events = (state.events ++ [event]) |> Enum.take(-@max_events)
    Arca.Cache.put({:exec_events, state.execution_id, state.org_id}, events, @buffer_ttl_ms)
    {:noreply, %{state | events: events}, @idle_timeout}
  end

  @impl true
  def handle_info(:timeout, state) do
    {:stop, :normal, state}
  end

  @impl true
  def handle_info(msg, state) do
    Logger.warning("#{__MODULE__}: unexpected message: #{inspect(msg)}")
    {:noreply, state, @idle_timeout}
  end

  @impl true
  def terminate(_reason, state) do
    if state.events != [] do
      key = {:exec_events, state.execution_id, state.org_id}

      # Merge with (never clobber) anything the direct-write fallback put in
      # the cache while this process existed — a wholesale put would erase
      # those events. Order can interleave; losing events cannot.
      cached =
        case Arca.Cache.get(key) do
          {:ok, existing} when is_list(existing) -> existing
          _ -> []
        end

      merged = Enum.uniq(cached ++ state.events) |> Enum.take(-@max_events)
      Arca.Cache.put(key, merged, @buffer_ttl_ms)
    end

    :ok
  end

  # ============================================================================
  # Private
  # ============================================================================

  # Route buffer writes through a per-execution GenServer to serialize them.
  # Falls back to direct cache write if the GenServer can't be started
  # (e.g., Registry not available in tests).
  defp buffer_event(execution_id, org_id, event) do
    case ensure_buffer(execution_id, org_id) do
      {:ok, pid} ->
        GenServer.cast(pid, {:buffer, event})

      :error ->
        # Fallback: direct write (non-atomic but functional)
        buffer_event_direct(execution_id, org_id, event)
    end
  end

  defp ensure_buffer(execution_id, org_id) do
    case Registry.lookup(Opus.ExecutionEventBuffer.Registry, execution_id) do
      [{pid, _}] ->
        {:ok, pid}

      [] ->
        case DynamicSupervisor.start_child(
               Opus.ExecutionEventBuffer.Supervisor,
               {__MODULE__, {execution_id, org_id}}
             ) do
          {:ok, pid} ->
            {:ok, pid}

          {:error, {:already_started, pid}} ->
            {:ok, pid}

          {:error, reason} ->
            # Not the "infrastructure absent" case — the supervisor is up
            # and refused. Log it: the direct-write fallback masks the
            # failure otherwise.
            Logger.warning(
              "#{__MODULE__}: start_child failed for #{execution_id}: #{inspect(reason)}"
            )

            :error
        end
    end
  rescue
    # Registry/Supervisor not started (e.g., in tests)
    _e in [ArgumentError, RuntimeError] -> :error
  end

  # Direct fallback for when GenServer infrastructure isn't available
  defp buffer_event_direct(execution_id, org_id, event) do
    key = {:exec_events, execution_id, org_id}

    events =
      case Arca.Cache.get(key) do
        {:ok, existing} -> existing
        :miss -> []
      end

    Arca.Cache.put(key, (events ++ [event]) |> Enum.take(-@max_events), @buffer_ttl_ms)
  end

  defp extract_org_id(%{org_id: org_id}),
    do: Arca.QueryHelpers.normalize_org_id(org_id)

  defp extract_org_id(_), do: Arca.QueryHelpers.normalize_org_id(nil)
end
