# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CYFR Works Inc.

defmodule Opus.ExecutionRecord do
  @moduledoc """
  Struct and storage for WASM execution records.

  Execution records capture the complete state of a component execution
  for auditing, debugging, and forensic replay purposes.

  ## Storage

  Records are stored in SQLite via `Arca.Execution` to the `executions` table.
  The crash-resilient
  pattern writes a "started" record BEFORE execution begins, and updates it with
  completion/failure data AFTER execution finishes.

  If an execution record exists with status "running" but no completion,
  the execution crashed or was interrupted.

  ## Usage

      # Create and write started record BEFORE execution
      record = ExecutionRecord.new(ctx, reference, input)
      :ok = ExecutionRecord.write_started(record)

      # Execute...

      # On success: write completion
      record = ExecutionRecord.complete(record, output)
      :ok = ExecutionRecord.write_completed(record)

      # On failure: write failure
      record = ExecutionRecord.fail(record, error)
      :ok = ExecutionRecord.write_failed(record)

  ## Correlation IDs

  All IDs use UUID v7 (RFC 9562) format for time-ordering:
  - `execution_id`: `exec_<uuid7>` - Generated by Opus for each execution
  - `request_id`: `req_<uuid7>` - From the MCP request context (if available)
  """

  require Logger

  alias Sanctum.Context

  @type t :: %__MODULE__{
          id: String.t(),
          request_id: String.t() | nil,
          user_id: String.t(),
          athanor_id: String.t() | nil,
          reference: String.t(),
          resolved_from: String.t() | nil,
          component_type: Opus.ComponentType.t(),
          component_digest: String.t() | nil,
          input: map(),
          output: map() | nil,
          status: :running | :completed | :failed | :cancelled,
          started_at: DateTime.t(),
          completed_at: DateTime.t() | nil,
          duration_ms: non_neg_integer() | nil,
          error: String.t() | nil,
          host_policy: map() | nil,
          parent_execution_id: String.t() | nil,
          root_execution_id: String.t() | nil,
          resolver_digest: String.t() | nil,
          activation_digest: String.t() | nil,
          activation_graph: String.t() | nil,
          profile_id: String.t() | nil
        }

  defstruct [
    :id,
    :request_id,
    :user_id,
    :athanor_id,
    :reference,
    :resolved_from,
    :component_type,
    :component_digest,
    :input,
    :output,
    :status,
    :started_at,
    :completed_at,
    :duration_ms,
    :error,
    :host_policy,
    :parent_execution_id,
    :root_execution_id,
    :resolver_digest,
    :activation_digest,
    :activation_graph,
    :profile_id,
    # The fence this attempt writes the row with (`Arca.Execution`).
    :attempt,
    # The invoking component's reference for a child (`Opus.Chain`); nil for
    # a root. Not a column — it decides what of the output is persisted.
    :parent_reference
  ]

  @doc """
  Create a new execution record when starting execution.

  Options:
  - `:component_type` - The component type (:catalyst, :reagent, :formula). Defaults to :reagent.
  - `:component_digest` - The SHA256 digest of the WASM component.
  - `:host_policy` - Snapshot of the host policy applied to this execution.
  - `:parent_execution_id` - Parent formula execution ID for sub-invocations.
  - `:root_execution_id` - The chain's root execution ID. A root stamps
    itself, so every row in a chain carries the same value.
  """
  @spec new(Context.t(), String.t(), map(), keyword()) :: t()
  def new(%Context{} = ctx, reference, input, opts \\ []) do
    component_type = Keyword.get(opts, :component_type, :reagent)
    component_digest = Keyword.get(opts, :component_digest)
    host_policy = Keyword.get(opts, :host_policy)
    parent_execution_id = Keyword.get(opts, :parent_execution_id)
    id = Keyword.get(opts, :execution_id) || generate_id()
    # A root execution is its own root: one comparison answers "is this
    # row in my chain" without walking parents.
    root_execution_id = Keyword.get(opts, :root_execution_id) || id

    %__MODULE__{
      id: id,
      request_id: ctx.request_id,
      user_id: ctx.user_id,
      athanor_id: ctx.athanor_id,
      reference: reference,
      component_type: component_type,
      component_digest: component_digest,
      input: input,
      output: nil,
      status: :running,
      started_at: DateTime.utc_now(),
      completed_at: nil,
      duration_ms: nil,
      error: nil,
      host_policy: host_policy,
      parent_execution_id: parent_execution_id,
      root_execution_id: root_execution_id,
      # Which consent rooted this run. `Opus.Chain.run_root/5` resolves the
      # profile before anything executes and passes its id here, so the row
      # records the authority rather than leaving it to be re-derived.
      profile_id: Keyword.get(opts, :profile_id),
      attempt: Cyfr.UUID7.generate_id("att"),
      parent_reference: Keyword.get(opts, :parent_reference)
    }
  end

  @doc "Mark execution as completed with output."
  @spec complete(t(), map()) :: t()
  def complete(%__MODULE__{} = record, output) do
    now = DateTime.utc_now()
    duration_ms = DateTime.diff(now, record.started_at, :millisecond)

    %{
      record
      | output: output,
        status: :completed,
        completed_at: now,
        duration_ms: duration_ms
    }
  end

  @doc "Mark execution as failed with error message."
  @spec fail(t(), String.t()) :: t()
  def fail(%__MODULE__{} = record, error) do
    now = DateTime.utc_now()
    duration_ms = DateTime.diff(now, record.started_at, :millisecond)

    %{
      record
      | status: :failed,
        error: error,
        completed_at: now,
        duration_ms: duration_ms
    }
  end

  @doc """
  Cancel a running execution.

  Only running executions can be cancelled. Returns:
  - `{:ok, record}` - Successfully cancelled
  - `{:error, :not_found}` - Execution not found
  - `{:error, :not_cancellable}` - Execution already completed/failed/cancelled
  """
  @spec cancel(Context.t(), String.t()) ::
          {:ok, t()} | {:error, :not_found | :not_cancellable | term()}
  def cancel(%Context{} = ctx, id) do
    case get(ctx, id) do
      {:ok, %{status: :running} = record} ->
        # `get/2` authorized the READ; cancelling is a mutation and takes the
        # :execute permission — every ingress funnels through here, so a
        # viewer credential cannot kill executions.
        case Context.authorize(ctx, :execute, {:execution, Map.from_struct(record)}) do
          :ok -> do_cancel(record)
          {:error, _} = error -> error
        end

      {:ok, _record} ->
        {:error, :not_cancellable}

      {:error, :not_found} ->
        {:error, :not_found}
    end
  end

  defp do_cancel(record) do
    now = DateTime.utc_now()
    duration_ms = DateTime.diff(now, record.started_at, :millisecond)

    cancelled_record = %{
      record
      | status: :cancelled,
        completed_at: now,
        duration_ms: duration_ms
    }

    case write_failed(cancelled_record) do
      :ok ->
        {:ok, cancelled_record}

      {:error, :not_running} ->
        # The run finished between the `:running` read above and this write
        # — the row's conditional guard refused the stamp, so the completed
        # result stands and nothing gets killed.
        {:error, :not_cancellable}

      error ->
        error
    end
  end

  # ============================================================================
  # Storage API (delegates to Arca.Execution)
  # ============================================================================

  @doc """
  Write execution start record BEFORE execution begins.

  This must be called before starting WASM execution to ensure crash resilience.

  The row carries an ENVELOPE of the input, never the input: the reference,
  a digest, sizes, the top-level keys and the attachments' digests. The
  assistant's root turn used to persist its whole composed prompt, the
  compacted history, every attachment as base64 and the room excerpt the
  guest was told was transient — and every model call, the full provider
  request — unredacted, ten thousand rows deep per athanor. Conversation
  content lives in `messages`; a component's input is the caller's to
  keep.
  """
  @spec write_started(t()) :: :ok | {:error, term()}
  def write_started(%__MODULE__{} = record) do
    case Arca.Execution.record_start(%{
           id: record.id,
           request_id: record.request_id,
           reference: encode_reference(record.reference),
           input_hash: Arca.Execution.hash_input(record.input),
           user_id: record.user_id,
           athanor_id: record.athanor_id,
           component_type: to_string(record.component_type),
           component_digest: record.component_digest,
           started_at: record.started_at,
           status: "running",
           input: encode_json(input_envelope(record)),
           host_policy: encode_json(record.host_policy),
           parent_execution_id: record.parent_execution_id,
           root_execution_id: record.root_execution_id,
           resolver_digest: record.resolver_digest,
           activation_digest: record.activation_digest,
           activation_graph: record.activation_graph,
           profile_id: record.profile_id,
           attempt: record.attempt,
           runner_id: runner_id(),
           lease_until: lease_until()
         }) do
      {:ok, _} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  # The lease a running row holds. Refreshed while the execution runs
  # (`Opus.Executor`); a row whose lease lapsed belongs to a runner that
  # stopped renewing — the sweeper fails it.
  @lease_seconds 180

  @doc "How long one lease renewal is good for."
  def lease_seconds, do: @lease_seconds

  @doc """
  This boot's name on an execution row (`Cyfr.Boot`), never `node()`:
  distribution is not configured, so every node was `nonode@nohost` and
  the sweeper could not tell its own lapsed lease from another node's
  crash. A restart is a different runner, which is what the sweeper needs.
  """
  @spec runner_id() :: String.t()
  def runner_id, do: Cyfr.Boot.id()

  @doc "A fresh lease expiry from now."
  def lease_until, do: DateTime.add(DateTime.utc_now(), @lease_seconds, :second)

  @doc """
  Renew the lease this attempt holds on its running row.

  `{:ok, until}` is the new expiry the row now carries. `:lost` means the
  row is no longer this attempt's to renew — it finished, the sweeper
  failed it, or the store could not answer — and the runner must stop
  authorized work once the lease it last held lapses.
  """
  @spec renew_lease(String.t(), String.t() | nil) :: {:ok, DateTime.t()} | :lost
  def renew_lease(execution_id, attempt) when is_binary(execution_id) do
    until = lease_until()

    case Arca.Execution.renew_lease(execution_id, until, attempt: attempt, runner_id: runner_id()) do
      1 -> {:ok, until}
      _ -> :lost
    end
  rescue
    e ->
      Logger.warning(
        "[ExecutionRecord] lease renewal failed for #{execution_id}: #{Exception.message(e)}"
      )

      :lost
  end

  @doc """
  Write execution completion record AFTER successful execution.
  """
  @spec write_completed(t()) :: :ok | {:error, term()}
  def write_completed(%__MODULE__{status: :completed} = record) do
    ctx = record_to_ctx(record)

    case Arca.Execution.record_complete(
           ctx,
           record.id,
           %{
             completed_at: record.completed_at,
             duration_ms: record.duration_ms,
             status: "completed",
             output: encode_json(persisted_output(record))
           },
           attempt: record.attempt
         ) do
      {:ok, _} ->
        retain_result(ctx, record)
        :ok

      {:error, reason} ->
        {:error, reason}
    end
  end

  def write_completed(%__MODULE__{status: status}) do
    {:error, "Cannot write completed record for status: #{status}"}
  end

  # A non-chat execution's result is kept as a payload in its own store,
  # by digest and retention class; the row keeps answering as it does. A
  # store that cannot keep it is logged, never the execution's failure.
  # Chat executions are the transcript's, not the payload store's.
  defp retain_result(ctx, %__MODULE__{} = record) do
    chat? = assistant_ref?(record.reference) or assistant_ref?(record.parent_reference)

    if not chat? and not is_nil(record.output) do
      case Arca.ExecutionPayloads.put(
             ctx,
             record.id,
             "result",
             encode_json(record.output),
             retention_class(record)
           ) do
        {:ok, _} ->
          :ok

        # A completion driven twice keeps the payload it already has.
        {:error, :exists} ->
          :ok

        {:error, reason} ->
          Logger.warning(
            "[Opus.ExecutionRecord] result payload of #{record.id} not retained: #{inspect(reason)}"
          )
      end
    end

    :ok
  end

  defp retention_class(%__MODULE__{user_id: "webhook:" <> _}), do: "webhook"
  defp retention_class(_record), do: "api"

  @doc """
  Write execution failure record AFTER failed or cancelled execution.
  """
  @spec write_failed(t()) :: :ok | {:error, term()}
  def write_failed(%__MODULE__{status: status} = record) when status in [:failed, :cancelled] do
    ctx = record_to_ctx(record)

    case Arca.Execution.record_complete(
           ctx,
           record.id,
           %{
             completed_at: record.completed_at,
             duration_ms: record.duration_ms,
             status: Atom.to_string(status),
             error_message: record.error
           },
           attempt: record.attempt
         ) do
      {:ok, _} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  def write_failed(%__MODULE__{status: status}) do
    {:error, "Cannot write failed record for status: #{status}"}
  end

  @doc """
  Load an execution record by ID.
  """
  @spec get(Context.t(), String.t()) :: {:ok, t()} | {:error, term()}
  def get(%Context{} = ctx, id) do
    case Arca.Execution.get_tenant(ctx, id) do
      nil ->
        {:error, :not_found}

      # get_tenant is db-rescued and answers a tuple on an outage. Bound as
      # the row it reaches execution_to_map/1, whose `is_struct or is_map`
      # guard raises — an outage read as a crash. Passed through, the
      # caller sees the storage refusal its siblings already answer.
      {:error, _} = err ->
        err

      record ->
        result = execution_to_map(record)

        case Context.authorize(ctx, :storage_read, {:execution, result}) do
          :ok -> {:ok, from_mcp_result(result)}
          {:error, _} -> {:error, :not_found}
        end
    end
  end

  @doc """
  List execution records for the context's athanor.

  Members of an athanor are interchangeable, so this returns the athanor's
  executions, not just the caller's own.

  Options:
  - `:limit` - Maximum number of records (default: 20)
  - `:status` - Filter by status (:running, :completed, :failed, :all)
  """
  @spec list(Context.t(), keyword()) :: {:ok, [t()]} | {:error, term()}
  def list(%Context{} = ctx, opts \\ []) do
    limit = Keyword.get(opts, :limit, 20)
    status_filter = Keyword.get(opts, :status, :all)

    opts = [
      limit: limit,
      athanor_id: ctx.athanor_id
    ]

    opts =
      if status_filter != :all,
        do: Keyword.put(opts, :status, to_string(status_filter)),
        else: opts

    records = Arca.Execution.list(opts)
    {:ok, Enum.map(records, fn r -> from_mcp_result(execution_to_map(r)) end)}
  end

  # ===========================================================================
  # Private - Struct Conversion
  # ===========================================================================

  defp from_mcp_result(result) when is_map(result) do
    %__MODULE__{
      id: result.id,
      request_id: result.request_id,
      user_id: result.user_id,
      athanor_id: result[:athanor_id],
      reference: parse_reference(result.reference),
      component_type: parse_component_type(result.component_type),
      component_digest: result.component_digest,
      input: parse_json_or_nil(result.input) || %{},
      output: parse_json_or_nil(result.output),
      status: parse_status(result.status),
      started_at: parse_datetime_value(result.started_at),
      completed_at: parse_datetime_value(result.completed_at),
      duration_ms: result.duration_ms,
      error: result.error_message,
      host_policy: parse_json_or_nil(result.host_policy),
      parent_execution_id: result[:parent_execution_id],
      root_execution_id: result[:root_execution_id],
      resolver_digest: result[:resolver_digest],
      activation_digest: result[:activation_digest],
      # The canonically-encoded graph string, exactly as stamped — never
      # decoded and re-encoded, which could break its canonical form.
      activation_graph: result[:activation_graph],
      profile_id: result[:profile_id]
    }
  end

  defp parse_json_or_nil(nil), do: nil

  defp parse_json_or_nil(json) when is_binary(json) do
    case Jason.decode(json) do
      {:ok, map} ->
        map

      {:error, _reason} ->
        Logger.warning(
          "[ExecutionRecord] Failed to parse stored JSON (#{byte_size(json)} bytes), returning nil"
        )

        nil
    end
  end

  defp parse_json_or_nil(other), do: other

  defp parse_reference(nil), do: nil
  defp parse_reference(ref) when is_binary(ref), do: ref
  defp parse_reference(other), do: inspect(other)

  defp parse_status(nil), do: :running
  defp parse_status("running"), do: :running
  defp parse_status("completed"), do: :completed
  defp parse_status("failed"), do: :failed
  defp parse_status("cancelled"), do: :cancelled

  defp parse_status(unknown) do
    Logger.warning(
      "[ExecutionRecord] Unrecognized status: #{inspect(unknown)}, treating as :unknown"
    )

    :unknown
  end

  defp parse_datetime_value(nil), do: nil
  defp parse_datetime_value(%DateTime{} = dt), do: dt

  defp parse_datetime_value(iso_string) when is_binary(iso_string) do
    case DateTime.from_iso8601(iso_string) do
      {:ok, dt, _offset} -> dt
      _ -> nil
    end
  end

  defp parse_datetime_value(_), do: nil

  # ===========================================================================
  # Private
  # ===========================================================================

  @doc """
  Generate a unique execution ID.

  Through `Cyfr.UUID7` like every other id in the system. It was the one
  holdout on `Ecto.UUID.generate/0` — random v4, so execution ids neither
  sorted by time nor inserted in index order, which is the property v7 was
  chosen for and which execution records, queried by time more than
  anything else, want most.
  """
  @spec generate_id() :: String.t()
  def generate_id, do: Cyfr.UUID7.execution_id()

  defp encode_reference(ref) when is_binary(ref), do: ref
  defp encode_reference(nil), do: nil
  defp encode_reference(other), do: inspect(other)

  defp encode_json(nil), do: nil
  defp encode_json(value) when is_binary(value), do: value

  defp encode_json(value), do: Cyfr.Json.safe_encode(value)

  # What the row keeps of the input: enough to say what ran and to tell
  # two inputs apart, nothing of what they said.
  defp input_envelope(%__MODULE__{} = record) do
    input = record.input || %{}
    encoded = Jason.encode!(input)

    %{
      "envelope" => "v1",
      "reference" => encode_reference(record.reference),
      "input_hash" => Arca.Execution.hash_input(input),
      "bytes" => byte_size(encoded),
      "keys" => input |> Map.keys() |> Enum.map(&to_string/1) |> Enum.sort()
    }
    |> put_attachment_digests(input)
  end

  defp put_attachment_digests(envelope, %{"attachments" => attachments})
       when is_list(attachments) do
    digests =
      for %{} = attachment <- attachments do
        data = attachment["data"] || attachment[:data] || ""

        %{
          "filename" => attachment["filename"] || attachment[:filename],
          "media_type" => attachment["media_type"] || attachment[:media_type],
          "bytes" => byte_size(data),
          "digest" => Cyfr.Digest.sha256(data)
        }
      end

    Map.put(envelope, "attachments", digests)
  end

  defp put_attachment_digests(envelope, _input), do: envelope

  # The assistant's own executions carry conversation content in their
  # OUTPUT too: the root turn returns the whole message array (the runner
  # reads it from the completion event, never from the row), and each
  # model call returns the provider's reply. Neither is the row's to keep:
  # the root keeps everything but the messages, a model call keeps a
  # digest, its size and the usage the planner needs. Every other
  # component's output is the caller's result and stays.
  @assistant_ref_prefix "formula:local.aqua"

  defp persisted_output(%__MODULE__{} = record) do
    cond do
      assistant_ref?(record.reference) and is_map(record.output) ->
        Map.drop(record.output, ["messages", :messages])

      assistant_ref?(record.parent_reference) and not is_nil(record.output) ->
        encoded = Jason.encode!(record.output)

        %{
          "envelope" => "v1",
          "output_hash" => Cyfr.Digest.sha256(encoded),
          "bytes" => byte_size(encoded),
          "usage" => usage_of(record.output)
        }

      true ->
        record.output
    end
  end

  defp assistant_ref?(ref) when is_binary(ref),
    do: String.starts_with?(ref, @assistant_ref_prefix)

  defp assistant_ref?(_), do: false

  defp usage_of(%{"usage" => usage}), do: usage
  defp usage_of(%{usage: usage}), do: usage
  defp usage_of(_), do: nil

  # The row's shape has one owner: the Ecto schema. The read map carries
  # every schema column except the lease mechanics, which belong to the
  # write path and the sweeper alone — `write_started` stamps them fresh
  # and nothing read back through here may act on them. A new column
  # flows into the map on its own; only `from_mcp_result/1` (the parser
  # layer) needs a decision about it.
  @row_only_fields [:runner_id, :lease_until]

  defp execution_to_map(record) when is_struct(record) or is_map(record) do
    Map.new(Arca.Execution.__schema__(:fields) -- @row_only_fields, fn field ->
      {field, Map.get(record, field)}
    end)
  end

  defp parse_component_type(nil), do: :reagent

  defp parse_component_type(type_str) when is_binary(type_str) do
    case Opus.ComponentType.parse(type_str) do
      {:ok, type} ->
        type

      {:error, _} ->
        require Logger

        Logger.warning(
          "[Opus.ExecutionRecord] Unknown component type: #{inspect(type_str)}, defaulting to :reagent"
        )

        :reagent
    end
  end

  defp parse_component_type(other) do
    raise ArgumentError,
          "Unexpected component type value: #{inspect(other)}. " <>
            "Expected nil, a binary string, or an atom."
  end

  # Rebuild a minimal context from execution record fields for tenant-scoped writes.
  # namespace is identity-only and not path-bearing, so it is omitted — the
  # row lands in the correct partition via athanor_id.
  defp record_to_ctx(%__MODULE__{} = record) do
    # Server-built write-back, but tenant-scoped to the originating athanor
    # (scope: :athanor + the record's athanor) so the row lands in the
    # correct partition. Routed through the single server-internal builder
    # (auth_method: :system).
    Sanctum.internal_context(
      user_id: record.user_id,
      athanor_id: record.athanor_id,
      permissions: [:execution_write],
      scope: :athanor
    )
  end
end
